"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](fg:peach bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:flamingo)\
$python\
[](fg:flamingo bg:lavender)\
$conda\
[](fg:lavender bg:pink)\
$time\
[](fg:pink bg:teal)\
$cmd_duration\
[ ](fg:teal)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:red fg:base"

[os.symbols]
Macos = " "

[username]
show_always = true
style_user = "bg:red fg:base"
style_root = "bg:red fg:base"
format = '[ $user ]($style)'

[directory]
style = "bg:peach"
format = '[[ 󱘈 $path ](fg:base bg:peach)]($style)'

[git_branch]
symbol = " " 
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:base bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:base bg:yellow)]($style)'

[python]
symbol = " "
style = "bg:flamingo"
format = '[[ $symbol( $version) ](fg:base bg:flamingo)]($style)'

[time]
disabled = false
style = "bg:pink fg:base"
format = '[ 󱁆 $time ]($style)'

[cmd_duration]
min_time = 5
style = "bg:teal"
format = '[[ 󱎫 $duration ](fg:mantle bg:teal)]($style)'

[conda]
symbol = " 󱓞 "
style = "bg:lavender"
format = '[[$symbol$environment ](fg:base bg:lavender)]($style)'

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
